### ISSUE TITLE
using bert or elmo?

### ISSUE THREAD

**Issue by NLPCL** [nlpcl-lab/mitigating-stereotypes-in-word-embedding#2]
hi @huijelee, I am doing the end-of-the-year check up.
I find the mitigation of stereotype is so very important for AI society
for designing an unbiased AI.

for that, is there any possibility for this model to be used for bert or elmo,
which uses the contextual information either, unlike simple word2vec?

thanks, yours sincerely, Yang

**Comment by huijelee** [comment]
Currently, our model can accept only word embedding as input, but we plan to handle stereotyped text in word piece or sentence-level units like BERT. As a way to use our current model, there may be a way to use the output of applying Word Piece embedding as input to our model instead of original Word Piece embedding used in BERT.

**Comment by NLPCL** [comment]
Internal Communication.
